#################################################################
#                                                               #
#           Home Assistant Main Configuration File              #
#                                                               #
#################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Zurich
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes/

default_config:

discovery:

http:
  base_url: !secret config_http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

api:

ios:

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db
  
#zwave:
#  usb_path: /dev/ttyUSB0

logger:
  default: error

recorder:
  purge_interval: 1
  purge_keep_days: 2